export const CAR_CONSULTA_WFS_URL = "https://consulta.car.gov.br/geoserver/ows";

export const CAR_CONSULTA_LAYERS = [
  { typeName: "consulta_publica:ast", rotulo: "Area do imovel - AST", tipoCamada: "area_imovel" },
  { typeName: "consulta_publica:area_consolidada", rotulo: "Area consolidada", tipoCamada: "outro" },
  { typeName: "consulta_publica:vegetacao_nativa", rotulo: "Vegetacao nativa", tipoCamada: "cobertura_solo" },
  { typeName: "consulta_publica:pct", rotulo: "Povos e comunidades tradicionais", tipoCamada: "outro" },
  { typeName: "consulta_publica:iru", rotulo: "Imovel rural em regularizacao", tipoCamada: "outro" },
  { typeName: "consulta_publica:arl_proposta", rotulo: "Reserva legal proposta", tipoCamada: "reserva_legal" },
  { typeName: "consulta_publica:arl_averbada", rotulo: "Reserva legal averbada", tipoCamada: "reserva_legal" },
  { typeName: "consulta_publica:arl_aprovada_nao_averbada", rotulo: "Reserva legal aprovada nao averbada", tipoCamada: "reserva_legal" },
  { typeName: "consulta_publica:area_servidao_administrativa_total", rotulo: "Servidao administrativa", tipoCamada: "servidao_administrativa" },
  { typeName: "consulta_publica:area_altitude_superior_1800", rotulo: "Area - altitude superior a 1800 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_declividade_maior_45", rotulo: "Area - declividade maior que 45", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_topo_morro", rotulo: "Area - topo de morro", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_pousio", rotulo: "Area de pousio", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_utilidade_publica", rotulo: "Area de utilidade publica", tipoCamada: "utilidade_publica" },
  { typeName: "consulta_publica:area_infraestrutura_publica", rotulo: "Infraestrutura publica", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_uso_restrito_declividade_25_a_45", rotulo: "Uso restrito - declividade 25 a 45", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_uso_restrito_pantaneira", rotulo: "Uso restrito - pantaneira", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_embargada", rotulo: "Area embargada", tipoCamada: "outro" },
  { typeName: "consulta_publica:area_entorno_reservatorio_energia", rotulo: "Entorno de reservatorio de energia", tipoCamada: "outro" },
  { typeName: "consulta_publica:banhado", rotulo: "Banhado", tipoCamada: "outro" },
  { typeName: "consulta_publica:borda_chapada", rotulo: "Borda de chapada", tipoCamada: "outro" },
  { typeName: "consulta_publica:lago_natural", rotulo: "Lago natural", tipoCamada: "outro" },
  { typeName: "consulta_publica:manguezal", rotulo: "Manguezal", tipoCamada: "outro" },
  { typeName: "consulta_publica:nascente_olho_dagua", rotulo: "Nascente/olho d'agua", tipoCamada: "outro" },
  { typeName: "consulta_publica:reservatorio_artificial_decorrente_barramento", rotulo: "Reservatorio artificial", tipoCamada: "outro" },
  { typeName: "consulta_publica:reservatorio_energia", rotulo: "Reservatorio de energia", tipoCamada: "outro" },
  { typeName: "consulta_publica:reservatorio_geracao_energia_ate_24_08_2001", rotulo: "Reservatorio de geracao ate 24/08/2001", tipoCamada: "outro" },
  { typeName: "consulta_publica:restinga", rotulo: "Restinga", tipoCamada: "outro" },
  { typeName: "consulta_publica:rio_ate_10", rotulo: "Rio ate 10 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:rio_10_a_50", rotulo: "Rio 10 a 50 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:rio_50_a_200", rotulo: "Rio 50 a 200 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:rio_200_a_600", rotulo: "Rio 200 a 600 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:rio_acima_600", rotulo: "Rio acima de 600 m", tipoCamada: "outro" },
  { typeName: "consulta_publica:vereda", rotulo: "Vereda", tipoCamada: "outro" },
  { typeName: "consulta_publica:app_area_altitude_superior_1800", rotulo: "APP - altitude superior a 1800 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_area_declividade_maior_45", rotulo: "APP - declividade maior que 45", tipoCamada: "app" },
  { typeName: "consulta_publica:app_area_topo_morro", rotulo: "APP - topo de morro", tipoCamada: "app" },
  { typeName: "consulta_publica:app_banhado", rotulo: "APP - banhado", tipoCamada: "app" },
  { typeName: "consulta_publica:app_borda_chapada", rotulo: "APP - borda de chapada", tipoCamada: "app" },
  { typeName: "consulta_publica:app_lago_natural", rotulo: "APP - lago natural", tipoCamada: "app" },
  { typeName: "consulta_publica:app_manguezal", rotulo: "APP - manguezal", tipoCamada: "app" },
  { typeName: "consulta_publica:app_nascente_olho_dagua", rotulo: "APP - nascente/olho d'agua", tipoCamada: "app" },
  { typeName: "consulta_publica:app_reservatorio_artificial_decorrente_barramento", rotulo: "APP - reservatorio artificial", tipoCamada: "app" },
  { typeName: "consulta_publica:app_reservatorio_geracao_energia_ate_24_08_2001", rotulo: "APP - reservatorio de energia", tipoCamada: "app" },
  { typeName: "consulta_publica:app_restinga", rotulo: "APP - restinga", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_lago_natural", rotulo: "APP - escadinha lago natural", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_nascente_olho_dagua", rotulo: "APP - escadinha nascente/olho d'agua", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_rio_ate_10", rotulo: "APP - escadinha rio ate 10 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_rio_10_a_50", rotulo: "APP - escadinha rio 10 a 50 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_rio_50_a_200", rotulo: "APP - escadinha rio 50 a 200 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_rio_200_a_600", rotulo: "APP - escadinha rio 200 a 600 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_rio_acima_600", rotulo: "APP - escadinha rio acima de 600 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_escadinha_vereda", rotulo: "APP - escadinha vereda", tipoCamada: "app" },
  { typeName: "consulta_publica:app_rio_ate_10", rotulo: "APP - rio ate 10 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_rio_10_a_50", rotulo: "APP - rio 10 a 50 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_rio_50_a_200", rotulo: "APP - rio 50 a 200 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_rio_200_a_600", rotulo: "APP - rio 200 a 600 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_rio_acima_600", rotulo: "APP - rio acima de 600 m", tipoCamada: "app" },
  { typeName: "consulta_publica:app_vereda", rotulo: "APP - vereda", tipoCamada: "app" },
];

export function montarNomeConsultaCAR(camada, codigoCAR) {
  const nomeCurto = String(camada.typeName || "").split(":").pop();
  return `${codigoCAR}_${nomeCurto}.geojson`;
}
